---

- hosts: all
  become: true
#"pre_tasks" makes the task first priority this means this task will be executed before all the rest BUT IN THIS CASE THERE WILL NOT BE A DIFFERENCE BECAUSE
#ANSIBLE EXECUTES FROM TOP TO BUTTOM 
  pre_tasks: 


  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu and Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu" and ansible_distribution == "Debian"

# Workstations group
- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    tags: unzip, terraform
    package:
      name: unzip

  - name: install terraform
    tags: unzip, terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

#web_servers group

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages on Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


#CentOS Related

# apt not exist in CentOS we replaced by "dnf"
# apache2 ==> httpd  && libapache2-mod-php ==> php

  - name: install httpd and php packages on CentOS
    tags: apache,centos,httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

#all copy files related

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

#db_servers group

- hosts: db_servers
  become: true
  tasks:
  
  - name: isntall mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

#file_servers grou^p
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

