---

- hosts: all
  become: true
#"pre_tasks" makes the task first priority this means this task will be executed before all the rest BUT IN THIS CASE THERE WILL NOT BE A DIFFERENCE BECAUSE
#ANSIBLE EXECUTES FROM TOP TO BUTTOM 
  pre_tasks: 


  - name: update repo cache (CentOS)
    tags: always
    dnf:
      update_cache: yes
#the chages for the "update_cache" won't be count for this part even if it was chaged the output will be cleaner :)
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu and Debian)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu" and ansible_distribution == "Debian"


#add the "devope" ssh public key to all the servers ./ssh/authorized_keys file
  - name: add ssh key for mounssim
    tags: always
    authorized_key: 
      user: mounssim
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILM9RwKDu+l9Dyf7yZf+cd7x/a/4DRD7eurd/PxbF5l0 Learning DevOps"


# Workstations group
- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    tags: unzip, terraform
    package:
      name: unzip

  - name: install terraform
    tags: unzip, terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

#web_servers group

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages on Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


#CentOS Related

# apt not exist in CentOS we replaced by "dnf"
# apache2 ==> httpd  && libapache2-mod-php ==> php

  - name: install httpd and php packages on CentOS
    tags: apache,centos,httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

# Start httpd service (CentOS)
  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
#enabled option will make sure httpd service is started even after restating the server
      enabled: yes
    when: ansible_distribution == "CentOS"

# Restarting a service

  - name: change email address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin kamala@gmail.com

    when: ansible_distribution == "CentOS"
    register: httpd

  - name: restart httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed
 

#all copy files related

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

#db_servers group

- hosts: db_servers
  become: true
  tasks:
  
  - name: isntall mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

#file_servers grou^p
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

