---

- hosts: all
  become: true
#"pre_tasks" makes the task first priority this means this task will be executed before all the rest BUT IN THIS CASE THERE WILL NOT BE A DIFFERENCE BECAUSE
#ANSIBLE EXECUTES FROM TOP TO BUTTOM 
  pre_tasks: 


  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu and Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu" and ansible_distribution == "Debian"

#web_servers group

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages on Ubuntu servers
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


#CentOS Related

# apt not exist in CentOS we replaced by "dnf"
# apache2 ==> httpd  && libapache2-mod-php ==> php

  - name: install httpd and php packages on CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"


#db_servers group

- hosts: db_servers
  become: true
  tasks:
  
  - name: isntall mariadb package (CentOS)
    dnf: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

#file_servers grou^p
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest

